### PR TITLE
Remove status subsystem

### PR DESCRIPTION
**Pull request by rhift**

### CODE REVIEW

**Comment by rhift** [comment]
@pmucha-55places I don't think that this is widely used enough to be a practical concern. In a future world we can make this better, but I want this to get deleted.

**Comment by rhift** [comment]
@pmucha-55places -
> I was browbeat into approving

å¬˚ß√∂˙√¬∆∫ œ˜øˆ¬˚å®ß≥≤˜√ ˚∆åƒ∂≤∫√ ˜˚´®¬åƒß√µ ˚ßfc

**Comment by jpmarcotte** [comment]
How difficult would it be to just have teardown remove all historical tables, and setup only create the ones it currently needs?

**Comment by rhift** [comment]
@jpmarcotte - that could work. I'll try to give it a shot if I have time.

**Comment by rhift** [comment]
@alexberryman @pmucha-55places @jpmarcotte - lemme know :)

**Pull request merged**
